import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import type { Dish, Order } from './types'

type RangeKey = '今日' | '昨日' | '近7日' | '近30日' | '自定义'
type SectionKey = '核心指标' | '营收分析' | '流量转化' | '盈利分析' | '热门商品' | '单品表现'
type DailyPoint = { date: string; sales: number; refund: number; turnover: number; received: number; orders: number; validOrders: number; diners: number; cost: number }
type Summary = Omit<DailyPoint, 'date'>
const sections: SectionKey[] = ['核心指标', '营收分析', '流量转化', '盈利分析', '热门商品', '单品表现']
const money = (value: number) => '¥' + value.toFixed(2)
const dateKey = (date: Date) => date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0')
const addDays = (date: Date, amount: number) => { const next = new Date(date); next.setDate(next.getDate() + amount); return next }
const datesBetween = (start: string, end: string) => { const dates: string[] = []; let cursor = new Date(start + 'T00:00:00'); const last = new Date(end + 'T00:00:00'); while (cursor <= last && dates.length < 366) { dates.push(dateKey(cursor)); cursor = addDays(cursor, 1) }; return dates }
const createDailyPoint = (date: string): DailyPoint => { const seed = Number(date.replaceAll('-', '')); const orders = 18 + (seed * 7) % 21; const validOrders = Math.max(0, orders - (seed % 6 === 0 ? 2 : seed % 4 === 0 ? 1 : 0)); const sales = orders * (58 + seed % 29); const refund = seed % 5 === 0 ? sales * .075 : seed % 3 === 0 ? sales * .028 : 0; const discount = sales * (.055 + (seed % 4) * .008); const turnover = Math.max(0, sales - refund); const received = Math.max(0, turnover - discount); return { date, sales, refund, turnover, received, orders, validOrders, diners: Math.round(validOrders * (2.1 + (seed % 4) * .25)), cost: received * (.43 + (seed % 5) * .015) } }
const summarize = (points: DailyPoint[]): Summary => points.reduce((total, point) => ({ sales: total.sales + point.sales, refund: total.refund + point.refund, turnover: total.turnover + point.turnover, received: total.received + point.received, orders: total.orders + point.orders, validOrders: total.validOrders + point.validOrders, diners: total.diners + point.diners, cost: total.cost + point.cost }), { sales: 0, refund: 0, turnover: 0, received: 0, orders: 0, validOrders: 0, diners: 0, cost: 0 })

function Comparison({ current, previous }: { current: number; previous: number }) {
  if (!previous) return <small className="finance-compare unavailable">上期数据不足，无法对比</small>
  const rate = (current - previous) / previous * 100
  return <small className={'finance-compare ' + (rate > 0 ? 'up' : rate < 0 ? 'down' : 'flat')}>{rate > 0 ? '↑' : rate < 0 ? '↓' : '—'}{Math.abs(rate).toFixed(2)}% <b>同比</b></small>
}
function MetricCard({ label, value, current, previous }: { label: string; value: string; current: number; previous: number }) { return <article className="finance-metric"><span>{label}</span><strong>{value}</strong><Comparison current={current} previous={previous} /></article> }
function LineChart({ points, field, color = '#246bd6', label }: { points: DailyPoint[]; field: 'sales' | 'turnover' | 'received' | 'validOrders'; color?: string; label: string }) {
  const width = 320; const height = 120; const padding = 14; const values = points.map(point => point[field]); const max = Math.max(...values, 1)
  const coords = values.map((value, index) => ({ x: padding + index * (width - padding * 2) / Math.max(values.length - 1, 1), y: height - padding - value / max * (height - padding * 2), value, date: points[index].date }))
  const path = coords.map((point, index) => (index ? 'L ' : 'M ') + point.x + ' ' + point.y).join(' ')
  return <div className="finance-line-chart"><svg viewBox={'0 0 ' + width + ' ' + height} role="img" aria-label={label}><line x1={padding} y1={height - padding} x2={width - padding} y2={height - padding} stroke="#e4eaf3" /><path d={path} fill="none" stroke={color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{coords.map(point => <circle key={point.date} cx={point.x} cy={point.y} r="3.5" fill="#fff" stroke={color} strokeWidth="2"><title>{point.date + '：' + (field === 'validOrders' ? point.value : money(point.value))}</title></circle>)}</svg><div><span>{points[0]?.date.slice(5)}</span><span>{points.at(-1)?.date.slice(5)}</span></div></div>
}
function CategoryDonut({ total, received = false }: { total: number; received?: boolean }) {
  const values = received ? [0.46, 0.31, 0.23] : [0.43, 0.34, 0.23]; const colors = ['#2c6bd4', '#67a7ec', '#f0b65b']; const labels = ['热菜', '甜品', '主食']; const first = values[0] * 100; const second = first + values[1] * 100
  const background = 'conic-gradient(' + colors[0] + ' 0 ' + first + '%,' + colors[1] + ' ' + first + '% ' + second + '%,' + colors[2] + ' ' + second + '% 100%)'
  return <div className="finance-donut-wrap"><div className="finance-donut" style={{ background }}><span><b>{money(total)}</b><small>{received ? '实收金额' : '营业总额'}</small></span></div><ul>{labels.map((item, index) => <li key={item}><i style={{ background: colors[index] }} /><span>{item}</span><b>{money(total * values[index])}</b><small>{(values[index] * 100).toFixed(0)}%</small></li>)}</ul></div>
}
function FinanceSection({ id, title, children }: { id: SectionKey; title: string; children: ReactNode }) { return <section className="finance-section" id={'finance-' + id} data-finance-section={id}><h2>{title}</h2>{children}</section> }

export function FinanceStatsPage({ orders: _orders, dishes, onBack }: { orders: Order[]; dishes: Dish[]; onBack: () => void }) {
  const today = new Date(); const yesterday = addDays(today, -1)
  const [range, setRange] = useState<RangeKey>('昨日'); const [startDate, setStartDate] = useState(dateKey(yesterday)); const [endDate, setEndDate] = useState(dateKey(yesterday))
  const [activeSection, setActiveSection] = useState<SectionKey>('核心指标'); const [heatMetric, setHeatMetric] = useState<'订单量' | '实收金额'>('订单量'); const [rankMetric, setRankMetric] = useState<'营收总额' | '毛利总额'>('营收总额')
  const [query, setQuery] = useState(''); const [sortKey, setSortKey] = useState<'sales' | 'received' | 'gross'>('received'); const [sortDesc, setSortDesc] = useState(true); const navRef = useRef<HTMLElement>(null)
  const applyPreset = (next: RangeKey) => { setRange(next); if (next === '自定义') return; const presetEnd = next === '昨日' ? yesterday : today; const length = next === '近7日' ? 7 : next === '近30日' ? 30 : 1; setEndDate(dateKey(presetEnd)); setStartDate(dateKey(addDays(presetEnd, -(length - 1)))) }
  const points = useMemo(() => datesBetween(startDate, endDate).map(createDailyPoint), [startDate, endDate])
  const previousPoints = useMemo(() => { const length = Math.max(points.length, 1); const previousEnd = addDays(new Date(startDate + 'T00:00:00'), -1); return datesBetween(dateKey(addDays(previousEnd, -(length - 1))), dateKey(previousEnd)).map(createDailyPoint) }, [startDate, points.length])
  const summary = useMemo(() => summarize(points), [points]); const previous = useMemo(() => summarize(previousPoints), [previousPoints])
  const avgOrder = summary.validOrders ? summary.received / summary.validOrders : 0; const previousAvgOrder = previous.validOrders ? previous.received / previous.validOrders : 0
  const perPerson = summary.diners ? summary.received / summary.diners : 0; const previousPerPerson = previous.diners ? previous.received / previous.diners : 0
  const refundRate = summary.sales ? summary.refund / summary.sales * 100 : 0; const previousRefundRate = previous.sales ? previous.refund / previous.sales * 100 : 0
  const gross = summary.received - summary.cost; const previousGross = previous.received - previous.cost; const grossRate = summary.received ? gross / summary.received * 100 : 0; const previousGrossRate = previous.received ? previousGross / previous.received * 100 : 0
  const costsComplete = dishes.length > 0 && dishes.every(dish => dish.estimatedCost !== undefined)
  const catalog = dishes.length ? dishes : [{ id: 'none', name: '暂无菜品', price: 0 } as Dish]
  const itemRows = useMemo(() => catalog.map((dish, index) => { const sales = Math.max(1, Math.round(summary.validOrders * (0.32 - index * 0.055))); const received = sales * dish.price * (dish.discount ? 1 - dish.discount / 100 : 1); const itemCost = sales * (dish.estimatedCost ?? 0); return { name: dish.name, sales, received, estimateRate: dish.estimatedCost === undefined || !dish.price ? null : (dish.price - dish.estimatedCost) / dish.price * 100, actualRate: dish.estimatedCost === undefined || !received ? null : (received - itemCost) / received * 100, gross: dish.estimatedCost === undefined ? null : received - itemCost, contribution: dish.estimatedCost === undefined || !gross ? null : (received - itemCost) / gross * 100 } }), [catalog, summary.validOrders, gross])
  const visibleRows = useMemo(() => [...itemRows].filter(row => row.name.includes(query.trim())).sort((a, b) => { const aValue = sortKey === 'sales' ? a.sales : sortKey === 'received' ? a.received : a.gross ?? -Infinity; const bValue = sortKey === 'sales' ? b.sales : sortKey === 'received' ? b.received : b.gross ?? -Infinity; return (aValue - bValue) * (sortDesc ? -1 : 1) }), [itemRows, query, sortKey, sortDesc])
  const ranked = [...itemRows].sort((a, b) => rankMetric === '营收总额' ? b.received - a.received : (b.gross ?? 0) - (a.gross ?? 0)).slice(0, 10); const salesRanked = [...itemRows].sort((a, b) => b.sales - a.sales).slice(0, 10)
  const heatValues = Array.from({ length: 24 }, (_, hour) => { const peak = Math.max(0, 13 - Math.abs(hour - 12)) + Math.max(0, 9 - Math.abs(hour - 19)); return heatMetric === '订单量' ? Math.round(peak * Math.max(summary.validOrders, 1) / 90) : peak * Math.max(summary.received, 1) / 65 }); const heatMax = Math.max(...heatValues, 1); const peakHour = heatValues.indexOf(heatMax)
  useEffect(() => { const observer = new IntersectionObserver(entries => { const visible = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActiveSection((visible.target as HTMLElement).dataset.financeSection as SectionKey) }, { rootMargin: '-170px 0px -45% 0px', threshold: [0.05, 0.25, 0.5] }); document.querySelectorAll('[data-finance-section]').forEach(element => observer.observe(element)); return () => observer.disconnect() }, [])
  useEffect(() => { navRef.current?.querySelector('.active')?.scrollIntoView({ inline: 'center', block: 'nearest', behavior: 'smooth' }) }, [activeSection])
  const goTo = (section: SectionKey) => { setActiveSection(section); document.getElementById('finance-' + section)?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  const changeSort = (next: typeof sortKey) => { if (sortKey === next) setSortDesc(value => !value); else { setSortKey(next); setSortDesc(true) } }
  const rankList = (rows: typeof itemRows, mode: 'amount' | 'sales') => <div className="finance-rank-list">{rows.map((row, index) => { const value = mode === 'sales' ? row.sales : rankMetric === '营收总额' ? row.received : row.gross ?? 0; const max = Math.max(...rows.map(item => mode === 'sales' ? item.sales : rankMetric === '营收总额' ? item.received : item.gross ?? 0), 1); return <div key={row.name}><b>{index + 1}</b><span>{row.name}</span><i><em style={{ width: value / max * 100 + '%' }} /></i><strong>{mode === 'sales' ? value + ' 份' : money(value)}</strong></div> })}</div>

  return <main className="finance-page">
    <header className="finance-header"><button aria-label="返回" onClick={onBack}>‹</button><h1>财务统计</h1><span /></header>
    <section className="finance-filter"><div className="finance-presets">{(['今日', '昨日', '近7日', '近30日', '自定义'] as RangeKey[]).map(item => <button className={range === item ? 'active' : ''} onClick={() => applyPreset(item)} key={item}>{item}</button>)}</div>{range === '自定义' && <div className="finance-custom-date"><input type="date" max={endDate} value={startDate} onChange={event => setStartDate(event.target.value)} /><span>至</span><input type="date" min={startDate} value={endDate} onChange={event => setEndDate(event.target.value)} /></div>}<p>统计周期：{startDate} 至 {endDate}</p></section>
    <nav className="finance-anchor-nav" ref={navRef}>{sections.map(section => <button className={activeSection === section ? 'active' : ''} onClick={() => goTo(section)} key={section}>{section}</button>)}</nav>
    <FinanceSection id="核心指标" title="核心指标概览"><div className="finance-metric-grid"><MetricCard label="营业总额" value={money(summary.turnover)} current={summary.turnover} previous={previous.turnover} /><MetricCard label="实收金额" value={money(summary.received)} current={summary.received} previous={previous.received} /><MetricCard label="有效订单数量" value={summary.validOrders + ' 单'} current={summary.validOrders} previous={previous.validOrders} /><MetricCard label="客单价" value={money(avgOrder)} current={avgOrder} previous={previousAvgOrder} /></div><div className="finance-chart-card"><h3>实收金额</h3><LineChart points={points} field="received" label="实收金额趋势" /></div><div className="finance-chart-card"><h3>菜品实收分析</h3><CategoryDonut total={summary.received} received /></div></FinanceSection>
    <FinanceSection id="营收分析" title="营收指标分析"><div className="finance-metric-grid"><MetricCard label="销售总额" value={money(summary.sales)} current={summary.sales} previous={previous.sales} /><MetricCard label="营业总额" value={money(summary.turnover)} current={summary.turnover} previous={previous.turnover} /><MetricCard label="退款金额" value={money(summary.refund)} current={summary.refund} previous={previous.refund} /><MetricCard label="退款率" value={refundRate.toFixed(2) + '%'} current={refundRate} previous={previousRefundRate} /></div><div className="finance-chart-card"><h3>营业总额</h3><LineChart points={points} field="turnover" color="#2d8b6f" label="营业总额趋势" /></div><div className="finance-chart-card"><h3>菜品营收分析</h3><CategoryDonut total={summary.turnover} /></div></FinanceSection>
    <FinanceSection id="流量转化" title="流量转化指标"><div className="finance-metric-grid"><MetricCard label="订单总数" value={summary.orders + ' 单'} current={summary.orders} previous={previous.orders} /><MetricCard label="有效订单数" value={summary.validOrders + ' 单'} current={summary.validOrders} previous={previous.validOrders} /><MetricCard label="客单价" value={money(avgOrder)} current={avgOrder} previous={previousAvgOrder} /><MetricCard label="人均消费" value={money(perPerson)} current={perPerson} previous={previousPerPerson} /></div><div className="finance-chart-card"><header><h3>营业时段热力图</h3><div className="finance-segment"><button className={heatMetric === '订单量' ? 'active' : ''} onClick={() => setHeatMetric('订单量')}>订单量</button><button className={heatMetric === '实收金额' ? 'active' : ''} onClick={() => setHeatMetric('实收金额')}>实收金额</button></div></header><div className="finance-heatmap">{heatValues.map((value, hour) => <div className={hour === peakHour ? 'peak' : ''} key={hour}><span style={{ height: Math.max(8, value / heatMax * 100) + '%' }} title={hour + ':00-' + hour + ':59 ' + heatMetric} /><small>{hour % 3 === 0 ? hour + ':00' : ''}</small></div>)}</div><p className="finance-peak">峰值时段：{peakHour}:00–{peakHour}:59</p></div><div className="finance-chart-card"><h3>有效订单数</h3><LineChart points={points} field="validOrders" color="#e39b32" label="有效订单数趋势" /></div></FinanceSection>
    <FinanceSection id="盈利分析" title="盈利指标分析">{costsComplete ? <><div className="finance-metric-grid finance-profit"><MetricCard label="商品总成本" value={money(summary.cost)} current={summary.cost} previous={previous.cost} /><MetricCard label="毛利总额" value={money(gross)} current={gross} previous={previousGross} /><MetricCard label="综合毛利率" value={grossRate.toFixed(2) + '%'} current={grossRate} previous={previousGrossRate} /></div><div className="finance-chart-card"><h3>盈利能力稳定性分析</h3><LineChart points={points} field="received" color="#8a64d6" label="盈利能力趋势" /></div></> : <div className="finance-cost-empty"><i>!</i><b>暂无法展示盈利数据</b><p>请在菜品管理中完善全部菜品的【单品预估成本】，完成后即可查看完整数据</p></div>}</FinanceSection>
    <FinanceSection id="热门商品" title="热门商品排行"><div className="finance-chart-card"><header><h3>单品营收/毛利 TOP10</h3><div className="finance-segment"><button className={rankMetric === '营收总额' ? 'active' : ''} onClick={() => setRankMetric('营收总额')}>按营收总额</button><button disabled={!costsComplete} title={!costsComplete ? '请在菜品管理中完善全部菜品的【单品预估成本】，完成后即可查看完整数据' : ''} className={rankMetric === '毛利总额' ? 'active' : ''} onClick={() => setRankMetric('毛利总额')}>按毛利总额</button></div></header>{rankList(ranked, 'amount')}</div><div className="finance-chart-card"><h3>单品销量 TOP10</h3>{rankList(salesRanked, 'sales')}</div></FinanceSection>
    <FinanceSection id="单品表现" title="单品表现分析"><div className="finance-item-toolbar"><label>⌕<input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索单品名称" /></label></div><div className="finance-table-wrap"><table><thead><tr><th>序号</th><th>单品名称</th><th><button onClick={() => changeSort('sales')}>单品销量 {sortKey === 'sales' ? sortDesc ? '↓' : '↑' : ''}</button></th><th><button onClick={() => changeSort('received')}>单品实收金额 {sortKey === 'received' ? sortDesc ? '↓' : '↑' : ''}</button></th><th className={!costsComplete ? 'disabled' : ''}>预估单品毛利率</th><th className={!costsComplete ? 'disabled' : ''}>实际单品毛利率</th><th className={!costsComplete ? 'disabled' : ''}><button disabled={!costsComplete} onClick={() => changeSort('gross')}>单品盈利总额</button></th><th className={!costsComplete ? 'disabled' : ''}>单品贡献率</th></tr></thead><tbody>{visibleRows.map((row, index) => <tr key={row.name}><td>{index + 1}</td><td>{row.name}</td><td>{row.sales}</td><td>{money(row.received)}</td><td className={!costsComplete ? 'disabled' : ''}>{row.estimateRate === null ? '待完善' : row.estimateRate.toFixed(2) + '%'}</td><td className={!costsComplete ? 'disabled' : ''}>{row.actualRate === null ? '待完善' : row.actualRate.toFixed(2) + '%'}</td><td className={!costsComplete ? 'disabled' : ''}>{row.gross === null ? '待完善' : money(row.gross)}</td><td className={!costsComplete ? 'disabled' : ''}>{row.contribution === null ? '待完善' : row.contribution.toFixed(2) + '%'}</td></tr>)}</tbody></table></div>{!costsComplete && <p className="finance-table-tip">灰色字段需完善全部菜品的【单品预估成本】后查看</p>}</FinanceSection>
  </main>
}
