import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './reset.css'
import './table.css'
import './search-layout.css'
import './table-detail.css'
import './order-core.css'
import './discount.css'
import './discount-current.css'
import './modal-close.css'
import './order-card-layout.css'
import './inventory-choice.css'
import './refund-close.css'
import './refund-amount.css'
import './add-table.css'
import './dish.css'
import './order-management.css'
import './service-requests.css'
import './service-category.css'
import './service-category-inline.css'
import './account-settings.css'
import './preference-settings.css'
import './language-select.css'
import './account-row-layout.css'
import './store-settings.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode><App /></StrictMode>,
)
